### ISSUE TITLE
Bar can get launchers and windows confused

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/fynedesk#106]
I have 2 running LXTerminal windows, and it is configured to be in my launcher.
Here you can see 2 LXTerminal icons in the launcher section, but the left hand one refers to a window as can be seen from it's context menu.
Restarting FyneDesk does not fix this issue, though it may place the two icons the other way round.
Perhaps relevant is that the other open LXTerminal does not seem to have an icon, when I iconified it it disappeared.

![Screenshot from 2020-05-07 13-41-08](https://user-images.githubusercontent.com/294436/81290636-51b07380-9060-11ea-8b6f-a795e77c9a5e.png)

**Comment by okratitan** [comment]
I haven't seen this.  Can you still reproduce and are there steps?

**Comment by andydotxyz** [comment]
Unfortunately no real steps. I have not seen it in a while.
What I am seeing, and may relate, is that over time the icons for open windows can disappear...

**Comment by andydotxyz** [comment]
Still no reproduction steps - but not seen it in a while

**Comment by AlbinoGeek** [comment]
This happens with Guake too (which is an overlay terminal.) Guake should **never** be in the taskbar, due to its window classes, but it gets in there somehow.
