### ISSUE TITLE
log out doesn't work

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#112]
I've already seen the log out button work but it doesn't work any more. It closes some apps but no log out.

It could be a problem while closing slack or teams which still run as daemon when closed but it doesn't work even if I kill them before clicking on logout

**Comment by andydotxyz** [comment]
After 10 seconds do you see a notification showing that you could not be logged out?
If all windows can be closed it should log out OK as we don't wait for daemons.
I guess if the message does not appear then you're not up to date with develop?

**Comment by mattboll** [comment]
Yes I've got the notification message but I don't know which apps can't be clause. I guess the problem is slack, if I launch only firefox it works
But if I kill slack I still can't logout, may be we could kill all the problematic apps/daemons ?

**Comment by andydotxyz** [comment]
I’m not sure, look at the code and you’ll see that it logs out as soon as 0 windows are open. So my guess is that something is open and either iconified or not visible somehow...

**Comment by andydotxyz** [comment]
There were some glitches around app quitting resolved recently - is this still an issue on latest develop?

**Comment by mattboll** [comment]
Seems to work for my usage at least, I'm closing
