### ISSUE TITLE
Allow to resize window that overflows

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#113]
sometimes windows are too big for the screen (an other issue could be open for that)
AFAIK there is only one way to reduce height of window, and if the bottom bar is out of the screen because the app overflows, then we can't do it anymore.

We could add a shortcut such as alt-click or alt-F7 to move window over the top to be able to grab the bottom or we could allow to grab the top border to resize.

Both solution should be implemented from my point of view

**Comment by andydotxyz** [comment]
Probably best addresed by allowing top-left/top/top-right drag handles

**Comment by andydotxyz** [comment]
Probably even just top left/top right would be ok, then it won’t risk interfering with the titlebar buttons

**Comment by andydotxyz** [comment]
Landed, now on `develop` for testing

**Comment by mattboll** [comment]
It works pretty well, I can resize with top right corner.

But resizing brave window (should be the same with chrome browser) it moves my slack window, which is weird. Evenmore, my slack window moved to the top, over the top of the screen and then I was unable to move the slack window anymore because the top bar wasn't visible.
And after a few minutes, fynedesk just crashed

**Comment by andydotxyz** [comment]
Is Chrome / Brave using the system borders?
I cannot replicate this with them on or off in Chrome.

**Comment by mattboll** [comment]
Without system borders. I was also able to move slack window by *moving* brave window. I clic on the brave top bar (stay clicked) move around the window and slack window moves too, so it may be totally unrelated to this issue

**Comment by andydotxyz** [comment]
I think that is probably related to the window-order fixes that @okratitan put in place to fix the DnD issues in Chrome.
As I'm pretty sure it is not related to this I will close the issue as complete (because this only affected system borders).
After the #156 is landed can you please test again and open a new ticket if the wrong windows are still moving?
