### ISSUE TITLE
Windows are leaving trails behind

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fynedesk#119]
Moving windows around causes trails to be left behind. Windows also feel "floaty" and do not follow the mouse when moving the mouse around quickly. Please look at the archive below for a video of what happens:

[trailing-and-floating-windows.zip](https://github.com/fyne-io/fynedesk/files/4852129/trailing-and-floating-windows.zip)

**Comment by andydotxyz** [comment]
Double check with latest develop as it's on FYne v1.3.2 now :)

**Comment by Jacalz** [comment]
It looks like it didn’t improve much sadly. Windows are still trailing a lot :(

**Comment by okratitan** [comment]
This should be resolved by two upcoming fixes we are aware of - the vsync stuff and concurrent configurewindow changes

**Comment by okratitan** [comment]
Leaving this open - I think we solved the feel "floaty" and don not follow the mouse when moving quickly portion of this but there still seems to be trails for @Jacalz when he is moving windows on the primary screen with the fyne window underneath.

**Comment by andydotxyz** [comment]
Pretty sure that adding compton will have fixed these. If you install that binary it will be a proper compositor.
In the future we will integrate similar code so it does not need an external app.
