### ISSUE TITLE
Errors in logfile when not using a laptop

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fynedesk#120]
Desktop computers generally doesn't have any brightness controls and/or batteries. Brightness is handled by the monitor itself and batteries aren't really a thing in desktops for the most part. However, fynedesk prints errors about missing these parts:
```log
2020/06/30 21:04:46 Error reading battery info open /sys/class/power_supply/BAT0/energy_now: no such file or directory
2020/06/30 21:04:46 Error reading brightness info strconv.ParseFloat: parsing "": invalid syntax
```

**Comment by Jacalz** [comment]
Alternatively, it might be good to automatically turn off battery and brightness in settings if the user are on a desktop.

**Comment by andydotxyz** [comment]
We don't know (in the toolkit) if this is a desktop. But this should gracefully turn off the checks...

**Comment by andydotxyz** [comment]
On develop for testing
