### ISSUE TITLE
go build fails: undefined: wm.NewX11WindowManager, undefined: wm.NewX11ScreensProvider

### ISSUE THREAD

**Issue by probonopd** [fyne-io/fynedesk#132]
```
user@FreeBSD$ uname -a
FreeBSD FreeBSD 12.1-RELEASE-p8 FreeBSD 12.1-RELEASE-p8 GENERIC  amd64

user@FreeBSD$ go version
go version go1.14.7 freebsd/amd64

user@FreeBSD$ go build -v fyne.io/fynedesk/cmd/fynedesk
fyne.io/fynedesk/cmd/fynedesk
# fyne.io/fynedesk/cmd/fynedesk
go/src/fyne.io/fynedesk/cmd/fynedesk/main_unix.go:18:14: undefined: wm.NewX11WindowManager
go/src/fyne.io/fynedesk/cmd/fynedesk/main_unix.go:23:39: undefined: wm.NewX11ScreensProvider
```

**Comment by andydotxyz** [comment]
With any luck the latest commit on `develop` may help with this.
What BSD do you recommend I set up to do more testing?

**Comment by probonopd** [comment]
Easiest is to grab a Live ISO from https://www.furybsd.org/ and boot it in a VM or from USB.

**Comment by andydotxyz** [comment]
Thanks, I got it up and running and had FyneDesk install under way but the build is killed part way through - I’m assuming out of memory or disk in the VM. Will try with a larger machine/config tomorrow.

**Comment by andydotxyz** [comment]
P.s. if you’re on gophers slack server we’re in #fynedesk :)

**Comment by andydotxyz** [comment]
resolved on develop :)
<img width="712" alt="Screenshot 2020-10-02 at 21 58 35" src="https://user-images.githubusercontent.com/294436/94969820-4d975d80-04fb-11eb-84ff-fb1c698938c1.png">

**Comment by probonopd** [comment]
Thanks @andydotxyz. What is the easiest way to install this from the develop branch?

**Comment by andydotxyz** [comment]
After the “go get” fails due to the error above then:

$ cd ~/go/src/fyne.io/fynedesk/cmd/fynedesk
$ git checkout develop
$ go install

Should be just fine :)

I’d recommend installing fynedesk_runner which is next to FyneDesk - if you use the runner then a crash will not lose your X session...

**Comment by probonopd** [comment]
Seeing 

```
user@FreeBSD$ go install
main_unix.go:13:2: build constraints exclude all Go files in /home/user/go/src/fyne.io/fynedesk/internal/x11/wm
```

Is this to be expected?

Also, there is nothing fyne-related to be found in `~/go/bin/` after the `go install`.

**Comment by andydotxyz** [comment]
That is not what should happen - are you definitely on develop branch? Which BSD are you on?

**Comment by probonopd** [comment]
```
user@FreeBSD$ cd ~/go/src/fyne.io/fynedesk/cmd/fynedesk

user@FreeBSD$ git status
On branch develop
Your branch is up to date with 'origin/develop'.
nothing to commit, working tree clean

user@FreeBSD$ uname -a
FreeBSD FreeBSD 12.1-RELEASE-p8 FreeBSD 12.1-RELEASE-p8 GENERIC  amd64
```

**Comment by Jacalz** [comment]
I would recommend trying to install by running `make` followed by `sudo make install`.

**Comment by andydotxyz** [comment]
> running `make`

Unfortunately that won't help if the go build command is failing

**Comment by Jacalz** [comment]
Yeah that’s true. I was mostly meaning it as a solution for getting it installed (not built). I have never personally got it to work by running `go install` ;)

**Comment by andydotxyz** [comment]
Ah! I forgot to say "git pull" after "git checkout" sorry @probonopd - perhaps that does it?

**Comment by probonopd** [comment]
Sure enough. Sorry for my stupid questions ;-)

__It works now__ :-) :+1:
