### ISSUE TITLE
App Menu in FyneDesk Develop (at Bar and as right-click mouse option)

### ISSUE THREAD

**Issue by computyx** [fyne-io/fynedesk#134]
Hello Everyone,

I am running FreeBSD 12.2-RC1 amd64 with latest pkgs and dmr-knod on an intel dell laptop.
I installed Fynedesk, per Andy instructions and help :+1: 
It works! and it is impressive.
I have few suggestions:
On the right lower corner - there is Application and a search option - that allowed me to search for an existing app (e.g. Hexchat or openoffice-write) click on it and start.

It would be useful to have a pull down menu - with a categorized (or not) list - showing the applications installed .

Of course - having that app menu available at RIGHT-CLICK mouse - it would be very usefull too...

Thanks for the great work!

Acu

**Comment by andydotxyz** [comment]
Right click could work - but I think we need to have a visible area to tap as well.

Should this pop out of a top-item on the user menu, or should we have a new button? i.e. "Launcher", "App menu", "User".
Could seem reduntant but somehow we should make a visible tap target to trigger this.

**Comment by computyx** [comment]
I think,  both,  having as a stand-alone button and pop-up menu option will be ergonomic.

I have three screens (Monitors) - but I can see that some people might want semitransparent gray bar  hidden - but yet a way to start applications should be easy.

**Comment by andydotxyz** [comment]
This should be resolved by the work in `feature/newmenu`, being presented in PR #204
