### ISSUE TITLE
How about a deterministic tiling engine?

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/fynedesk#153]
It's the tool that **automatically organize** the application's **windows** for you in a **predictable** and mutually **non-overlapping** disposition.

![](https://raw.githubusercontent.com/material-shell/material-shell/master/documentation/tiling_showcase.gif)

Choose at any time which tiling layout suit the most for your need:

-    **Maximize**: Single window at a time
-    **Split**: 2 windows side by side
-    **Column**: All windows displayed as columns (useful for ultra wide monitor)
-    **Half**: One master window on the left then others windows stacked to the right
-    **Grid**: All windows displayed as a grid

Relates to: #118 

---

Lifted from [Material Shell](https://github.com/material-shell/material-shell)

**Comment by andydotxyz** [comment]
I think that the only tiling we expect to incorporate is tracked in #118.
Of course we could find a way to make this available through external modules in the future.
