### ISSUE TITLE
Moving windows on external screens shows screen tearing

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fynedesk#161]
Moving around windows on the external screen shows excessive screen tearing. I guess that it is not property v-synced (double buffered?) to the refresh rate of the monitor or something along those lines. It is quite visually jarring to look at.

**Comment by okratitan** [comment]
This is a vsync issue that can be fixed by adjusting gfx card settings and @Jacalz confirmed adjusting his nvidia settings fixed this.  Apparently using a fyne window as root hides the tearing however so a workaround could be using a fyne window as root for additional screens other than primary.

**Comment by andydotxyz** [comment]
Yeah, closing as won't fix - X config resolves it
