### ISSUE TITLE
Settings and about should not open more than one window

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fynedesk#162]
At the moment, opening settings or about will create a new window, even if you have one open. I would prefer if it instead focused and brought the already open window to the front instead of opening new ones each time. Especially useful when you have a whole bunch of windows open.

https://user-images.githubusercontent.com/25466657/107670918-87d7ef00-6c93-11eb-8626-7b2a20df550b.mp4

**Comment by andydotxyz** [comment]
Resolved on develop
