### ISSUE TITLE
Applications can push other ones off the screen

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fynedesk#163]
Moving around windows sometimes allows for pushing other ones off the screen. Video was too big to upload here, please see https://gophers.slack.com/archives/CKV7AF2N6/p1613061709261800.

**Comment by okratitan** [comment]
I think the mouse events are probably getting propogated now to windows below and thus causing drags on other windows too to happen - could probably fix by grabbing the mouse during move/resizes and then ungrabbing when done.
