### ISSUE TITLE
handle chrome apps

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#184]
I use videostream, which is a "chrome app"
https://chrome.google.com/webstore/detail/videostream-for-google-ch/cnciopoikihiagdjbjpnocolokfelagl?hl=en

If I use the applications launcher, I can't find the app when I type "videostream" (it works with gnome)
When I run the app, it does not appear in the bottom app bar and it misses an icon on alt-tab

**Comment by andydotxyz** [comment]
Do you know anything about how the chrome apps are "installed" or where the metadata is stored?

**Comment by mattboll** [comment]
I've spent 5 minutes to find how to launch the app when it doesn't work with the launcher so I'm not an expert.

I have found some files in `~/.config/google-chrome/Default/Extensions/cnciopoikihiagdjbjpnocolokfelagl/2.20.505.0_0/videostream.nmf`

But I don't know how to find standalone apps

After some google, I'm not even sure it's still supported by chrome

**Comment by andydotxyz** [comment]
From what I have read on stackexchange I wonder if they should be installed at `/home/$USER/.local/share/applications`.
I think we already index that location, but there may be a mistake in our code?...

**Comment by mattboll** [comment]
It may be a bug then : 
```
$ pwd
/home/mbollot/.local/share/applications
$ cat chrome-cnciopoikihiagdjbjpnocolokfelagl-Default.desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Videostream for Google Chromecast™
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=cnciopoikihiagdjbjpnocolokfelagl
Icon=chrome-cnciopoikihiagdjbjpnocolokfelagl-Default
StartupWMClass=crx_cnciopoikihiagdjbjpnocolokfelagl
```

**Comment by andydotxyz** [comment]
I wonder if it is an issue with the icon lookup path, I think that we did not add a user-home based location but I'm not sure.
Will investigate.

**Comment by andydotxyz** [comment]
It seems that Google has sttopped supporting this already, and will remove them completely.
Am I reading about a different feature? https://www.theverge.com/2020/1/15/21067907/google-chrome-apps-end-support-lune-windows-macos-linux

**Comment by mattboll** [comment]
Yeah, I guess we should just not take care of chrome apps, I'm closing :)

**Comment by andydotxyz** [comment]
I managed to get this working on macOS because I had some Chrome apps installed.
Then I went to Linux and tried to set some up, and realised Google will not let you do that any more.
I think you're right there is not much to be done here :(.
