### ISSUE TITLE
Unplug screen doesn't work

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#185]
I use an external screen, disable my laptop screen. When I unplug the external screen, my laptop screen stays disable (and totally black)

Nvidia, linux Debian, gdm… please ask me if you need any information

**Comment by andydotxyz** [comment]
I think this could be a duplicate of #81.
What tool do you use to disable the laptop screen when the monitor is plugged in?

**Comment by mattboll** [comment]
Oops sorry, totally a duplicate I didn't see it. I'm using arandr from the settings

**Comment by andydotxyz** [comment]
Not a problem.
This is in part due to the bug linked, but also part that arandr is not linking to events at all.
Really we need a more complete solution so that the desktop knows your preference and tries to maintain it through these changes. Hopefully something for the next release.
