### ISSUE TITLE
Documentation update for Ubuntu/Debian based systems

### ISSUE THREAD

**Issue by metacatdud** [fyne-io/fynedesk#187]
On the install page aside from **gcc** for ubuntu/debian based system you also need:
```
- libgl1-mesa-dev
- xorg-dev
```
libraries to be installed in order to work

EDIT: 
https://developer.fyne.io/ on Install section
Also, you can close this. 
I saw there is an URL to getting started where is more platform-specific (https://developer.fyne.io/started/)

Sorry! My bad :)

**Comment by andydotxyz** [comment]
I'm sorry, I can't see which install page you are referring to. Can you provide the URL to the documentation that needs updated please?

**Comment by Jacalz** [comment]
@metacatdud I will close this given the information that you provided in the edit. In the future, please send a response with updated information, because we don't get notified when you edit the content of the issue.
