### ISSUE TITLE
Add calculator key support for launching the fyne calculator

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/fynedesk#194]
My laptop has a special "Calc" key that opens the calculator correctly in both Gnome and on Windows 10 (possibly in other places as well). It would be very cool too hook this up in FyneDesk as well and have it launch the fyne calculator there as well. I might tackle this in the future, but if anyone feels inclined to get it fixed, I will add it here in the meantime. I think it should be a relatively good first issue for new contributors :)

**Comment by andydotxyz** [comment]
Can you capture the key code somehow? Without that data or your keyboard I’m not sure how we can wire it up ;)

**Comment by Jacalz** [comment]
Do you have a good idea for how to do that? I tried inside fyne_demo but Gnome just launched the calculator without any input coming up in the application window 😅

**Comment by andydotxyz** [comment]
Probably something like xinput or any X event printing app.

**Comment by Jacalz** [comment]
Looks like this is the output from `xev` with keycode 148:
```
KeyPress event, serial 34, synthetic NO, window 0x1600001,
    root 0x7cc, subw 0x0, time 1193498, (377,226), root:(383,261),
    state 0x0, keycode 148 (keysym 0x1008ff1d, XF86Calculator), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by andydotxyz** [comment]
Thanks, added on `develop` ready for next release
