### ISSUE TITLE
Go get command fails

### ISSUE THREAD

**Issue by ilovefreesw** [fyne-io/fynedesk#205]
Can't install it using `go get` command as mentioned in the docs.

![image](https://user-images.githubusercontent.com/77317006/135575552-688ccea3-2484-4bc5-92e7-1144f024321b.png)

Tried using `go install` but still fails.

![image](https://user-images.githubusercontent.com/77317006/135575638-2fe32ecd-c034-4810-8188-fec6ce961604.png)

How to fix this?

I am on Ubuntu 20.04 and go version go1.17.1 linux/amd64

**Comment by andydotxyz** [comment]
The first error you saw was a deprecation warning, not an error. It will have completed successfully.

**Comment by ilovefreesw** [comment]
alright..thx
