### ISSUE TITLE
Make alt-shift-tab work as expected

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#208]
Right now, alt-shift-tab works the same as alt-tab, it looks like this line : 
`	shift := ev.State&xproto.ModMaskShift != 0`
is not working. In events.go l174 the boolean is always false

**Comment by andydotxyz** [comment]
You might need to add more context, because this seems to be working for many.

**Comment by mattboll** [comment]
As talked on slack, Alt-Shift on my debian install switch the keymap so I guess it is why it isn't working for me. If I switch Alt to Super, It works as expected

**Comment by mattboll** [comment]
I'm closing the bug because it's not a fynedesk issue.
I was able to fix this problem by reconfiguring the keyboard on debian
`sudo dpkg-reconfigure keyboard-configuration`
