### ISSUE TITLE
Compilation instructions are incomplete

### ISSUE THREAD

**Issue by taigrr** [fyne-io/fynedesk#221]
### Describe the bug:
Currently, we have a list of runtime prerequisites, but no compile-time prerequisites.
Having golang, git, and make installed before attempting to compile are easy assumptions to make, but the following are also required:

- libx11-dev
- libxcursor-dev
- libxrandr-dev
- libxinerama-dev
- libxcb-xinput-dev
- libxi-dev
- libgl-dev
- libxxf86vm-dev

### To Reproduce:
Steps to reproduce the behaviour:
1. Install ubuntu desktop
2. Install git, make, and golang
3. Follow the instructions in the readme

Is this something worth adding to the readme?

**Comment by andydotxyz** [comment]
Maybe we can link to the Fyne docs, as the compile time requirements are the same?

**Comment by taigrr** [comment]
#235 resolves this issue. Closing.
