### ISSUE TITLE
Shortcuts are not working when numlock is on

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#224]
When we have num lock activated, ev.State contains the numlock value so the shortcuts are not triggered (alt-space, alt-L etc.)

### Device (please complete the following information):
 - **OS:** Debian
 - **Version:** Sid
 - **Go version:** 1.18
 - **FyneDesk version:** develop

**Comment by andydotxyz** [comment]
On `develop` for testing.
