### ISSUE TITLE
DND in Chrome not dropping or hovering

### ISSUE THREAD

**Issue by okratitan** [fyne-io/fynedesk#49]
This doesn't work at the moment - a new window for the tab you start dragging is created.

**Comment by andydotxyz** [comment]
Perhaps this will fix the drag in Arandr as well?

**Comment by okratitan** [comment]
https://www.freedesktop.org/wiki/Specifications/XDND/

I think we will have to support these hints

**Comment by andydotxyz** [comment]
This is merged down into `release/v0.1.2` branch for testing. Do you think we can solve the Chrome issue in time for release? that plus VLC look like the only remaining issues :)

**Comment by andydotxyz** [comment]
Leaving open because despite the hard work Chrome drag is still not right.

**Comment by andydotxyz** [comment]
I can't find specific code in other WM like i3 that this works OK in.
I suspect that some of our mouse grab code could be blocking this mistakenly.

**Comment by andydotxyz** [comment]
Oh man somehow this has become an issue again!
I can't currently see what changed but will try and bisect soon and track it down.

**Comment by andydotxyz** [comment]
Ignore this, it started working again.
A lot of things were broken on my computer, just add this to the list!_
